platform: 10.11.92.33

workspace:
  base: /go
  path: src/github.com/jaegertracing/jaeger

clone:
  git:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-git:1.0
    dns: 223.5.5.5
    when:
      branch:
        - dev

pipeline:

  jaeger-ui:
    image: registry.cn-qingdao.aliyuncs.com/wod/jaeger-ui:v1.12.0
    commands:
      - rm -rf jaeger-ui
      - mkdir -p jaeger-ui/packages/jaeger-ui/build
      - cp -r /opt/jaeger/www/* jaeger-ui/packages/jaeger-ui/build/
    when:
      branch:
        - dev

  build:
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.15.6-alpine
    dns: 223.5.5.5
    volumes:
      - /data/cache/golang/pkg/:/go/pkg/ 
    environment:
      - GOPROXY=https://goproxy.cn
    commands:
      - mkdir -p dist
      - bash .beagle/build.sh
    when:
      branch:
        - dev

  docker:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.12
    dockerfile: .beagle/dockerfile
    repo: wod/jaegertracing
    version: v1.21.0
    channel: alpha
    args: "TARGETOS=linux,TARGETARCH=amd64"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets:
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - dev

  harbor:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/jaegertracing:v1.21.0-alpha
    target: registry.cn-qingdao.aliyuncs.com/wod/jaegertracing:v1.21.0
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  docker-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.12-arm64
    dockerfile: .beagle/dockerfile
    repo: wod/jaegertracing
    version: v1.21.0
    channel: alpha-arm64
    args: "TARGETOS=linux,TARGETARCH=amd64"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - dev

  harbor-arm64:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/jaegertracing:v1.21.0-alpha-arm64
    target: registry.cn-qingdao.aliyuncs.com/wod/jaegertracing:v1.21.0-arm64
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master
        
  docker-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.12-ppc64le
    dockerfile: .beagle/dockerfile
    repo: wod/jaegertracing
    version: v1.21.0
    channel: alpha-ppc64le
    args: "TARGETOS=linux,TARGETARCH=amd64"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - dev

  harbor-ppc64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/jaegertracing:v1.21.0-alpha-ppc64le
    target: registry.cn-qingdao.aliyuncs.com/wod/jaegertracing:v1.21.0-ppc64le
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master

  docker-mips64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.11-mips64le
    dockerfile: .beagle/dockerfile
    repo: wod/jaegertracing
    version: v1.21.0
    channel: alpha-mips64le
    args: "TARGETOS=linux,TARGETARCH=amd64"
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - dev

  harbor-mips64le:
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-tag:1.0
    dns: 223.5.5.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    source: registry.cn-qingdao.aliyuncs.com/wod/jaegertracing:v1.21.0-alpha-mips64le
    target: registry.cn-qingdao.aliyuncs.com/wod/jaegertracing:v1.21.0-mips64le
    registry: registry.cn-qingdao.aliyuncs.com
    secrets: 
      - source: REGISTRY_USER_ALIYUN
        target: REGISTRY_USER
      - source: REGISTRY_PASSWORD_ALIYUN
        target: REGISTRY_PASSWORD
    when:
      branch:
        - master